pre-commit:
  parallel: true
  commands:
    circular-dependencies:
      run: npx madge --circular ./src/index.ts
      skip: 
        - rebase
    dead-code:
      run: npx knip
      skip: 
        - rebase
    spelling:
      run: npx cspell {staged_files} --quiet
      skip: 
        - rebase
    style:
      run: npx @biomejs/biome check --write --no-errors-on-unmatched --files-ignore-unknown=true --colors=off {staged_files}
      stage_fixed: true
      skip: 
        - rebase
    types:
      run: npx tsc-files --noEmit {staged_files}
      skip: 
        - rebase
commit-msg:
  parallel: true
  commands: 
    validate-commit: 
      run: node ./.extras/validate-commit-message.mjs
      skip: 
        - rebase
pre-push:
  parallel: true
  commands:
    validate-branch-name:
      run: npx validate-branch-name
    audit-dependencies:
      run: npm audit --omit=dev
