services:
  service:
    build:
      context: .
      args:
        NODE_VERSION: 22
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: [ "node", "--watch", "--env-file", ".env", "src/index.ts" ]
