const ErrorCode = {
  API_UNSUPPORTED_FILTER_FIELD_OPERATOR: 'API_UNSUPPORTED_FILTER_FIELD_OPERATOR',
  API_UNSUPPORTED_FILTER_FIELD_VALUE: 'API_UNSUPPORTED_FILTER_FIELD_VALUE',
  API_UNSUPPORTED_FILTER_FIELD: 'API_UNSUPPORTED_FILTER_FIELD',
  API_UNSUPPORTED_FILTER_MULTIPLE_VALUE_OPERATOR: 'API_UNSUPPORTED_FILTER_MULTIPLE_VALUE_OPERATOR',
  API_UNSUPPORTED_FILTER_OPERATOR: 'API_UNSUPPORTED_FILTER_OPERATOR',
  API_UNSUPPORTED_SORT_FIELD: 'API_UNSUPPORTED_SORT_FIELD',
  APP_CONFIG_INCOMPLETE: 'APP_CONFIG_INCOMPLETE',
  UNHANDLED_EXCEPTION: 'UNHANDLED_EXCEPTION',
} as const

type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

export { ErrorCode }
