name: CI
on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  pull-requests:
    if: github.repository == 'n8io/typescript-service-template'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: 🛒 Checkout code
      - uses: actions/setup-node@v4
        name: 📗 Setup NodeJs
        with:
          node-version-file: '.nvmrc'
          cache: "npm"
      - name: 🔽 Install dependencies
        run: npm install --frozen-lockfile
      - name: 🔍 Audit dependencies
        run: npm audit
      - name: 🚨 Lint code
        run: npm run lint
      - name: 🧪 Run tests
        run: npm run test
      - name: 📔 Report coverage
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
